// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcWfbf-ZY6esGhO461bXEoF_TeyiObOz8',
    appId: '1:1091378404911:web:5b2daa7a0547ff167770da',
    messagingSenderId: '1091378404911',
    projectId: 'facetagram-ebb15',
    authDomain: 'facetagram-ebb15.firebaseapp.com',
    storageBucket: 'facetagram-ebb15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACkBdY5V2xs5ns3bKuXKey2X95vAMZYG8',
    appId: '1:1091378404911:android:1dccfd82c3772a7b7770da',
    messagingSenderId: '1091378404911',
    projectId: 'facetagram-ebb15',
    storageBucket: 'facetagram-ebb15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSHUapx6Gp1LT0bZdxnEgIBoxTn_L8hQk',
    appId: '1:1091378404911:ios:f41b8a48d7edf3687770da',
    messagingSenderId: '1091378404911',
    projectId: 'facetagram-ebb15',
    storageBucket: 'facetagram-ebb15.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

}